function cm_triangle_get_aabb(triangle)
{
	return [min(CM_TRIANGLE_X1, CM_TRIANGLE_X2, CM_TRIANGLE_X3),
			min(CM_TRIANGLE_Y1, CM_TRIANGLE_Y2, CM_TRIANGLE_Y3),
			min(CM_TRIANGLE_Z1, CM_TRIANGLE_Z2, CM_TRIANGLE_Z3),
			max(CM_TRIANGLE_X1, CM_TRIANGLE_X2, CM_TRIANGLE_X3),
			max(CM_TRIANGLE_Y1, CM_TRIANGLE_Y2, CM_TRIANGLE_Y3),
			max(CM_TRIANGLE_Z1, CM_TRIANGLE_Z2, CM_TRIANGLE_Z3)];
} 